name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 2 * * 1-5"
  workflow_dispatch:

jobs:
  build-chrome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in Chrome
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
        env:
          TERM: xterm

      - name: Generate Chrome report name
        if: always()
        id: generate_chrome_report_name
        run: |
          timestamp=$(date +"%Y%m%d%H%M%S")
          report_name="${timestamp}-chrome-cucumber-report"
          echo "CHROME_REPORT_NAME=${report_name}" >> $GITHUB_ENV

      - name: Rename Chrome Cucumber Report
        if: always()
        run: mv cypress/report/html cypress/report/${{ env.CHROME_REPORT_NAME }}

      - name: Upload Chrome Cucumber Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CHROME_REPORT_NAME }}
          path: cypress/report/${{ env.CHROME_REPORT_NAME }}

  build-edge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in Edge
        uses: cypress-io/github-action@v6
        with:
          browser: edge
        env:
          TERM: xterm

      - name: Generate Edge report name
        if: always()
        id: generate_edge_report_name
        run: |
          timestamp=$(date +"%Y%m%d%H%M%S")
          report_name="${timestamp}-edge-cucumber-report"
          echo "EDGE_REPORT_NAME=${report_name}" >> $GITHUB_ENV

      - name: Rename Edge Cucumber Report
        if: always()
        run: |
          if [ -d "cypress/report/html" ]; then
            mv cypress/report/html cypress/report/${{ env.EDGE_REPORT_NAME }}
          fi

      - name: Upload Edge Cucumber Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EDGE_REPORT_NAME }}
          path: cypress/report/${{ env.EDGE_REPORT_NAME }}
